config/routes.rb
BoatBooker::Application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :bookings
  root to: 'bookings#index'

end

app/models/booking.rb
require 'date'

class Booking < ActiveRecord::Base
  attr_accessible :book_from, :book_to, :user_id

  belongs_to :user

  validates :book_from, :book_to, :user, presence: true

  BOAT_SEASON = %w{ Mar Apr May Jun Jul Aug Sep Oct }
  BOOKING_TIMES = (8..22).to_a

  def self.build_booking(params, user)
    year = DateTime.now.year
    month = params[:date][:month].to_i
    day = params[:date][:day].to_i
    from = params[:book][:from].to_i
    to = params[:book][:to].to_i

    book_from = DateTime.new(year, month, day, from)
    book_to   = DateTime.new(year, month, day, to)

    Booking.new(book_from: book_from, book_to: book_to, user_id: user.id)
  end

  def self.month_options
    options = []
    BOAT_SEASON.each {|month| options << [ month, Date::ABBR_MONTHNAMES.index(month) ]}
    return options
  end

  def self.day_options
    options = []
    (1..31).to_a.collect {|d| options << [ sprintf("%02d", d), d ] }
    return options
  end

  def self.from_time_options
    options = []
    BOOKING_TIMES.each {|time| options << [ Booking::pretty_time(time), time ]}
    return options.shift(BOOKING_TIMES.length - 1)
  end

  def self.to_time_options
    options = []
    BOOKING_TIMES.each {|time| options << [ Booking::pretty_time(time), time ]}
    return options.slice(1..BOOKING_TIMES.length - 1)
  end

  def self.pretty_time(time)
    sprintf("%02d:00", time)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :password

  has_many :bookings

  has_secure_password

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    flash.keep
    @bookings = Booking.find(:all)
  end

  def new
    @month_options = Booking.month_options
    @day_options = Booking.day_options
    @from_time_options = Booking.from_time_options
    @to_time_options = Booking.to_time_options
    @booking = Booking.new
  end

  def create
    @booking = Booking.build_booking(params, current_user)

    if @booking.save
      flash[:notice] = "Your booking was saved successfully"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update_attributes(params[:booking])
      flash[:notice] = "Your booking was successfully updated"
      redirect_to root_path
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in!'
      redirect_to root_url
    else
      flash[:notice] = 'Name or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out!'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boat_booker_date(date)
    date.strftime("%d/%m/%Y")
  end

  def boat_booker_time(time)
    time.strftime("%H:%M")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/edit.html.haml
-# views/booking/edit.html.haml

%h1= boat_booker_date(Time.now)

= form_for @booking do |f|
  = f.label :book_from, 'From'
  = time_select(:booking, :book_from, { minute_step: 15, prompt: true })
  = f.label :book_to, 'To'
  = time_select(:booking, :book_to, { minute_step: 15, prompt: true })
  = submit_tag 'Update'

app/views/bookings/index.html.haml
-# views/booking/index.html.haml

%h1 Oxford Medley Boat Club
%p= link_to("Create new booking", new_booking_path)
%table#bookings
  %caption Bookings
  %thead
    %tr
      %th Date
      %th From
      %th To
      %th Skipper
  - @bookings.each do |booking|
    %tr
      %td #{boat_booker_date(booking.book_from)}
      %td #{boat_booker_time(booking.book_from)}
      %td #{boat_booker_time(booking.book_to)}
      %td #{booking.user.name}
-#      %td= link_to "Edit", edit_booking_path(booking)

app/views/bookings/new.html.haml
-# views/booking/new.html.haml

%h1 Oxford Medley Boat Club

%h2 New Booking

= form_for @booking do |f|
  %div
    = label_tag :date, 'Date:'
    = select('date', 'day', @day_options, { include_blank: true })
    %span /
    = select('date', 'month', @month_options, { include_blank: true })
  %div
    = label_tag :book, 'From:'
    = select('book', 'from', @from_time_options, { include_blank: true })
    = label_tag :book, 'To:'
    = select('book', 'to', @to_time_options, { include_blank: true })
  %div
    = submit_tag 'Book it!'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BoatBooker
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #login-bar
      - if current_user
        Logged in as #{current_user.name}
        = link_to 'Log out', logout_path
      - else
        - if current_page?(login_path)
          = link_to 'Back', root_path
        - else
          = link_to 'Log in', login_path


    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]

    = yield